import { z } from "zod";

export const host_schema = z.object({
  /* needed when create */
  name: z.string(),
  height: z.number().int().min(1).max(4),
  is_running: z.boolean(),
  dc_id: z.string().uuid(),
  room_id: z.string().uuid(),
  rack_id: z.string().uuid(),

  service_id: z.string().uuid().optional(),
  ip: z.string().ip().optional(),

  /* generated by backend */
  id: z.string().uuid().nullable(),
});

export const rack_schema = z.object({
  /* needed when create */
  name: z.string(),
  height: z.number().int().min(1).max(60),
  dc_id: z.string(),
  room_id: z.string(),

  service_id: z.string().uuid().optional(),
  n_hosts: z.number().int().min(0),
  hosts: z.array(
    host_schema.extend({
      pos: z.number().int().min(1).max(60),
    }),
  ),

  /* generated by backend */
  id: z.string().uuid().nullable(),
});

export const room_schema = z.object({
  /* needed when create */
  name: z.string(),
  height: z.number().int().min(1).max(60),
  dc_id: z.string().uuid(),

  service_id: z.string().uuid().optional(),
  n_hosts: z.number().int().min(0),
  n_racks: z.number().int().min(0),
  racks: z.array(rack_schema),

  /* generated by backend */
  id: z.string().uuid().nullable(),
});

export const datacenter_schema = z.object({
  /* needed when create */
  name: z.string(),
  height: z.number().int().min(1).max(60),

  n_hosts: z.number().int().min(0),
  n_racks: z.number().int().min(0),
  n_rooms: z.number().int().min(0),
  rooms: z.array(room_schema),

  /* generated by backend */
  id: z.string().uuid().nullable(),
});

export const service_schema = z.object({
  /* needed when create */
  name: z.string(),
  n_racks: z.number().int().min(1).max(60),

  /* generated by backend */
  racks: z.array(rack_schema),
  ip_list: z.array(z.string().ip()),
  id: z.string().uuid().nullable(),
});
