import { z } from "zod";

export const host_schema = z.object({
  /* needed when create */
  name: z.string(),
  height: z.number().int().min(1).max(4),
  is_running: z.boolean(),
  dc_id: z.string().uuid(),
  room_id: z.string().uuid(),
  rack_id: z.string().uuid(),

  /* update by frontend */
  ip: z.string().ip().optional(),

  /* generated by backend */
  id: z.string().uuid().nullable(),
});

export const rack_schema = z.object({
  /* needed when create */
  name: z.string(),
  height: z.number().int().min(1).max(60),
  n_hosts: z.number().int().min(0),
  dc_id: z.string(),
  room_id: z.string(),

  /* update by frontend */
  service_id: z.string().uuid().optional(),
  hosts: z.array(
    host_schema.extend({
      pos: z.number().int().min(1).max(60),
    }),
  ),

  /* generated by backend */
  id: z.string().uuid().nullable(),
});
